### ISSUE TITLE
文件下载失败

### ISSUE THREAD

**Issue by YouYouLip** [noneplugin/nonebot-plugin-petpet#199]
nonebot_plugin_petpet | Error downloading https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-petpet/v0.3.x/resources/resource_list.json, retry 2/3: Redirect response '302 FOUND' for url 'https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-petpet/v0.3.x/resources/resource_list.json'
Redirect location: 'https://fastly.jsdelivr.net/gh/noneplugin/nonebot-plugin-petpet@v0.3.x/resources/resource_list.json'
For more information check: https://httpstatuses.com/302
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<check_resources() done, defined at D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_petpet\download.py:58> exception=Exception('https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-petpet/v0.3.x/resources/resource_list.json 下载失败！')>
Traceback (most recent call last):
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_petpet\download.py", line 60, in check_resources
    (await download_resource("resource_list.json")).decode("utf-8")
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_petpet\download.py", line 48, in download_resource
    return await download_url(resource_url(path))
  File "D:\NoneBot-LingYin\LittlePaimon\.venv\lib\site-packages\nonebot_plugin_petpet\download.py", line 31, in download_url
    raise Exception(f"{url} 下载失败！")
Exception: https://ghproxy.com/https://raw.githubusercontent.com/noneplugin/nonebot-plugin-petpet/v0.3.x/resources/resource_list.json 下载失败！

**Comment by YouYouLip** [comment]
挂梯子改节点也还是报错 是原地址的问题吗

**Comment by MeetWq** [comment]
ghproxy 挂了，可以用 jsdelivr
设置 `petpet_resource_url` 为 `https://fastly.jsdelivr.net/gh/noneplugin/nonebot-plugin-petpet@v0.3.x/resources`
