### ISSUE TITLE
部分图片下载出错

### ISSUE THREAD

**Issue by yoiyami96** [noneplugin/nonebot-plugin-petpet#52]
目前出错的表情有关注、玩游戏、小天使、兑换券、我朋友说，报错日志为：
04-25 11:32:55 [SUCCESS] nonebot | ONEBOT V11 3558036990 | [message.group.normal]: Message -1686640642 from 1986612158@[群:722970667] "小天使 罗德岛种马 自己"
04-25 11:32:55 [INFO] nonebot | Event will be handled by <Matcher from src.plugins.petpet, type=message, priority=12, temp=False>
04-25 11:32:56 [WARNING] src | Traceback (most recent call last):
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\petpet\__init__.py", line 140, in handle
    res = await make_image(command, sender, users, args=args)
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\petpet\data_source.py", line 88, in make_image
    return await command.func(users, sender=sender, args=args)
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\petpet\functions.py", line 315, in littleangel
    await draw_text(
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\petpet\utils.py", line 61, in draw_text
    if all([char not in UNICODE_EMOJI["en"] for char in text]):
  File "C:\Users\cyy19\Downloads\software\amiya\bot\.\src\plugins\petpet\utils.py", line 61, in <listcomp>
    if all([char not in UNICODE_EMOJI["en"] for char in text]):
KeyError: 'en'

**Comment by MeetWq** [comment]
你检查一下 "emoji" 包是不是要求的版本

**Comment by yoiyami96** [comment]
> 你检查一下 "emoji" 包是不是要求的版本

是我铸币了，还在用emoji0.5.4,装了最新版好了
