### ISSUE TITLE
插件加载失败了

### ISSUE THREAD

**Issue by Hanx152** [noneplugin/nonebot-plugin-petpet#66]
05-28 11:30:02 [ERROR] nonebot | Failed to import "nonebot_plugin_petpet"
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\python\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\python\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "D:\python\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "D:\python\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\python\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "D:\python\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "D:\python\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "D:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\BOT\nb2\.\bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "D:\python\lib\site-packages\nonebot\plugin\load.py", line 119, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "D:\python\lib\site-packages\nonebot\plugin\load.py", line 53, in load_all_plugins
    return manager.load_all_plugins()
  File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 128, in load_all_plugins
    return set(
  File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 129, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.list_plugins()))
> File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "D:\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "D:\python\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\python\lib\site-packages\nonebot_plugin_petpet\__init__.py", line 17, in <module>
    from .data_source import make_image, commands
  File "D:\python\lib\site-packages\nonebot_plugin_petpet\data_source.py", line 5, in <module>
    from .utils import to_image
  File "D:\python\lib\site-packages\nonebot_plugin_petpet\utils.py", line 14, in <module>
    from emoji.unicode_codes import UNICODE_EMOJI
  File "D:\python\lib\site-packages\emoji\__init__.py", line 19, in <module>
    from emoji.core import *
  File "D:\python\lib\site-packages\emoji\core.py", line 16, in <module>
    from emoji import unicode_codes
  File "D:\python\lib\site-packages\emoji\unicode_codes\__init__.py", line 3, in <module>
    from emoji.unicode_codes.data_dict import *
ModuleNotFoundError: No module named 'emoji.unicode_codes.data_dict'

**Comment by MeetWq** [comment]
检查一下 emoji 包的版本

**Comment by Hanx152** [comment]
![ALJ@ K5ZF)RO7JE6WO~VTJ2](https://user-images.githubusercontent.com/103246532/170814024-3192e1f4-65e3-4362-a437-17a40402c678.png)
是这个吗

**Comment by Hanx152** [comment]
好了好了，谢谢大佬
