### ISSUE TITLE
插件加载失败 ModuleNotFoundError: No module named '_ctypes'

### ISSUE THREAD

**Issue by Ra1n-qwq** [noneplugin/nonebot-plugin-petpet#88]
如题，操作系统为Centos7.6;Python 3.7.12 ;NoneBot2 v2.0.0-beta.4
尝试用nb-cli安装，载入nonebot_plugin_imageutils成功，但无法载入nonebot_plugin_petpet，尝试采用本地文件载入，也载入失败。
以下是bot.py使用nonebot.load_plugins(“”)方法载入时的报错
```
07-08 18:16:01 [SUCCESS] nonebot | NoneBot is initializing...
07-08 18:16:01 [INFO] nonebot | Current Env: dev
07-08 18:16:01 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
07-08 18:16:01 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
07-08 18:16:01 [SUCCESS] nonebot | Succeeded to import "echo"
07-08 18:16:02 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_imageutils"
07-08 18:16:02 [ERROR] nonebot | Failed to import "nonebot_plugin_petpet"
Traceback (most recent call last):
  File "bot.py", line 24, in <module>
    nonebot.load_plugins("src/plugins/nonebot-plugin-petpet")
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 173, in load_all_plugins
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 149, in load_plugin
    self._path_to_module_name(self._searched_plugin_names[name])
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xxx/awabot/src/plugins/nonebot-plugin-petpet/nonebot_plugin_petpet/__init__.py", line 13, in <module>
    from .data_source import commands
  File "/home/xxx/awabot/src/plugins/nonebot-plugin-petpet/nonebot_plugin_petpet/data_source.py", line 1, in <module>
    from .utils import Command
  File "/home/xxx/awabot/src/plugins/nonebot-plugin-petpet/nonebot_plugin_petpet/utils.py", line 3, in <module>
    import imageio
  File "/usr/local/lib/python3.7/site-packages/imageio/__init__.py", line 24, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/usr/local/lib/python3.7/site-packages/imageio/core/__init__.py", line 13, in <module>
    from .findlib import load_lib
  File "/usr/local/lib/python3.7/site-packages/imageio/core/findlib.py", line 10, in <module>
    import ctypes
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
07-08 18:16:02 [WARNING] __main__ | Always use `nb run` to start the bot instead of manually running!
07-08 18:16:02 [SUCCESS] nonebot | Running NoneBot...
07-08 18:16:02 [DEBUG] nonebot | Loaded adapters: OneBot V11
07-08 18:16:02 [INFO] uvicorn | Will watch for changes in these directories: ['/home/xxx/awabot']
07-08 18:16:02 [INFO] uvicorn | Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
07-08 18:16:02 [INFO] uvicorn | Started reloader process [9145] using watchgod
07-08 18:16:02 [SUCCESS] nonebot | NoneBot is initializing...
07-08 18:16:02 [INFO] nonebot | Current Env: dev
07-08 18:16:02 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
07-08 18:16:02 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
07-08 18:16:02 [SUCCESS] nonebot | Succeeded to import "echo"
07-08 18:16:03 [SUCCESS] nonebot | Succeeded to import "nonebot_plugin_imageutils"
07-08 18:16:03 [ERROR] nonebot | Failed to import "nonebot_plugin_petpet"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/local/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/usr/local/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/usr/local/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/xxx/awabot/bot.py", line 24, in <module>
    nonebot.load_plugins("src/plugins/nonebot-plugin-petpet")
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/load.py", line 39, in load_plugins
    return manager.load_all_plugins()
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 173, in load_all_plugins
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 173, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 149, in load_plugin
    self._path_to_module_name(self._searched_plugin_names[name])
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/usr/local/lib/python3.7/site-packages/nonebot/plugin/manager.py", line 237, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/xxx/awabot/src/plugins/nonebot-plugin-petpet/nonebot_plugin_petpet/__init__.py", line 13, in <module>
    from .data_source import commands
  File "/home/xxx/awabot/src/plugins/nonebot-plugin-petpet/nonebot_plugin_petpet/data_source.py", line 1, in <module>
    from .utils import Command
  File "/home/xxx/awabot/src/plugins/nonebot-plugin-petpet/nonebot_plugin_petpet/utils.py", line 3, in <module>
    import imageio
  File "/usr/local/lib/python3.7/site-packages/imageio/__init__.py", line 24, in <module>
    from .core import FormatManager, RETURN_BYTES
  File "/usr/local/lib/python3.7/site-packages/imageio/core/__init__.py", line 13, in <module>
    from .findlib import load_lib
  File "/usr/local/lib/python3.7/site-packages/imageio/core/findlib.py", line 10, in <module>
    import ctypes
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
```

**Comment by MeetWq** [comment]
应该是 `centos` 的问题，可以自行搜索 `centos No module named '_ctypes'`
