### ISSUE TITLE
ImportError: cannot import name 'PluginMetadata' from 'nonebot.plugin' 

### ISSUE THREAD

**Issue by PROBEFISH** [noneplugin/nonebot-plugin-petpet#90]
大佬这个我启动后就会提示缺少东西这个怎么解决啊
[ERROR] nonebot | Failed to import "nonebot_plugin_petpet"
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\bot\probe\bot.py", line 33, in <module>
    nonebot.load_plugin('nonebot_plugin_petpet')
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\load.py", line 28, in load_plugin
    return manager.load_plugin(module_path)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 104, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\manager.py", line 194, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot_plugin_petpet\__init__.py", line 7, in <module>
    from nonebot.plugin import PluginMetadata
ImportError: cannot import name 'PluginMetadata' from 'nonebot.plugin' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\nonebot\plugin\__init__.py)

**Comment by MeetWq** [comment]
升级 nonebot 到 b4

**Comment by KafCoppelia** [comment]
貌似b3就行了
