### ISSUE TITLE
字体中找不到 ’bold‘

### ISSUE THREAD

**Issue by leinlin** [noneplugin/nonebot-plugin-petpet#97]
07-25 10:06:03 [ERROR] nonebot | Running matcher <Matcher from ATRI.plugins.nonebot_plugin_petpet, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.9/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 668, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/matcher.py", line 635, in simple_run
    await handler(
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 89, in __call__
    values = await self.solve(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/dependencies/__init__.py", line 196, in solve
    value = await field_info._solve(**params)
  File "/usr/local/lib/python3.9/dist-packages/nonebot/internal/params.py", line 155, in _solve
    solved = await task
  File "/usr/local/lib/python3.9/dist-packages/nonebot/utils.py", line 111, in _wrapper
    result = await loop.run_in_executor(None, pfunc)
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/ATRI/ATRI/plugins/nonebot_plugin_petpet/functions.py", line 305, in littleangel
    frame.draw_text(
TypeError: draw_text() got an unexpected keyword argument 'weight'

![image](https://user-images.githubusercontent.com/30318270/180679391-0798eb6a-366d-46f8-bd5b-12a39616dc5f.png)

**Comment by MeetWq** [comment]
更新 [nonebot-plugin-imageutils](https://github.com/noneplugin/nonebot-plugin-imageutils)
